"""Initial tables

Revision ID: cc76bf5e931a
Revises: 
Create Date: 2025-06-24 15:33:33.512677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc76bf5e931a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collo', sa.String(length=50), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=True),
    sa.Column('quantita', sa.Integer(), nullable=True),
    sa.Column('locazione', sa.Enum('vertiv', 'trascoop'), nullable=True),
    sa.Column('matricola', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('upload_data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pictures')
    op.drop_table('items')
    # ### end Alembic commands ###
